<h2>CombiGame</h2>
Game objectives: click on combinations of three figures where color, count, shape, and fill,
are either the same or all different. <br/>
<p>
<img style="height: 1.5em; width: 1.5em;" src="/images/give-up.png"> shows a valid combination among the figures.<br>
<img style="height: 1.5em; width: 1.5em;" src="/images/difficulty.png"> sets difficulty •&nbsp;easy: ca. 6 valid combinations •&nbsp;hard: 1 valid combination •&nbsp;normal: random number of valid combinations.<br>
<img style="height: 1.5em; width: 1.5em;" src="/images/score.png"> shows latest timing for the current difficulty.</p>
Click to close.
