<style>
    @import url(http://fonts.googleapis.com/css?family=Ubuntu:400);
    body { font-family: 'Ubuntu', sans-serif; margin: 0px; padding: 0px; font-size: 13pt; }
    #portrait { float: left; width: 77.6pt; height: 99pt; margin: 18pt 18pt 0pt 36pt; }
    .name { font-size: 18pt; padding: 36pt 0pt 0pt 72pt; }
    .contact{ font-size: 9pt; margin-top: -3pt; padding: 0pt 0pt 0pt 72pt; }
    .jobdesc { font-size: 18pt; padding: 9pt 0pt 36pt 72pt; }
    .section { padding: 0pt 0pt 36pt 36pt }
    .section div { padding: 6pt 0pt 0pt 36pt; }
</style>

<div class="name">Rasmus&thinsp;Erik &thinsp;&#64;&thinsp; solsort.dk</div>
<div class="contact">Muldager 32 2th, DK-2700 Brønshøj. +45 60703081</div>
<div class="jobdesc">- software developer at DBC a/s, <br/> and freelance computer scientist.</div>

<div class="section">
    Current areas of focus:
    <div>Mobile and web-apps • development, teaching, and strategy</div>
    <div>Open Source • infrastructure, and reusing existing solutions</div>
    <div>JavaScript • consulting, best practises, and scripting engines</div>
</div>

<hr>

<div class="section">
    Recent (a lot of these are experiments and may only work in modern browsers, ie. Firefox, Chromium or similar):
    <div>2012-03-21 <a href="#combigame">Combigame</a> early prototype of a Set™-like game for mobile devices</div>
    <div>2012-03-20 <a href="https://github.com/solsort/solsort.github.com">Github repository for solsort.com</a> with code/content from solsort.dk</div>
    <div>2012-03-18 <a href="#notes/speak-eval">Notes</a> for a presentation on speech evaluation at Toastmasters</div>
    <div>2012-03-16 <a href="#bidiv">Experiment</a> with layout based on binary division of space</div>
    <div>2012-03-11 <a href="/docs/server.html">JavaScript development server / bundling tool</a> started</div>
    <div>2012-03-10 <a href="http://solsort.dk/osd2012">Serious JavaScript - presentation at OpenSourceDays 2012</a></div>
    <div>2012-02-25 <a href="#menu">Experiment</a> with 2d-layout of hierarchical data</div>
    <div>2011-08-28 <a href="http://solsort.dk/planetcute">Simple app experiment</a> for game with the planetcute tileset</div>
    <div>2011-08-02 <a href="http://solsort.dk/dkcities">Simple app</a> for learning the danish citynames</div>
    <div>2011-05-24 <a href="http://solsort.dk/notescore">Simple app</a> for learning notes/scores on piano (<a href="https://play.google.com/store/apps/details?id=dk.solsort.notescore">https://play.google.com/store/apps/details?id=dk.solsort.notescore</a></div>
    <div><a href="http://github.com/rasmuserik/">Various other projects at GitHub</a></div>
</div>
